import React from 'react';

const About = () => {
    return (
        <div className='bgc p-3 '>
            <h1>About</h1>
            Mission
            Interesting and Intriguing, India offers incredible holiday experiences through its cultural, topography, and wildlife diversity. With these amazing and unique experiences, this south Asian country conveniently finds its way into the world tourism map as one of the finest destinations for a holistic vacation.

India establishes its identity as the country of architectural masterpieces, making it an ideal travel destination to plan a heritage tour in the world. While Taj Mahal makes for the major draw on an India tour, there are a plethora of monuments and edifices in every India travel guide displaying the fine architecture and grandiose of different eras in the country.

The diverse Indian topography adorned with the impressive Himalayas; long stretches of coastline; expansive hot, cold and white salt deserts; dense forests; alpine meadows and lakes; and scenic waterfalls pique the tourists’ interest.

Along with the best nature sightseeing tours, India offers an opportunity to visitors to have a little adventure of their own. The numerous spell-binding and less-trodden trails give trekking tour opportunities in South Asia unlike any other.

India Tours offers a chance to explore its biodiversity in the country's many national parks and wildlife reserves. An enthralling experience entails in the India wildlife tour packages that take tourists to the habitats of Royal Bengal Tigers, one-horned rhinos, and snow leopards amongst many rare, endangered, and unique species of flora and fauna.
Safety. Security. Service. Our highest priority is to protect the lives and interests of U.S. citizens overseas. We do this through routine and emergency services to Americans at our embassies and consulates around the world. We serve our fellow citizens during their most important moments – births, deaths, disasters, arrests, and medical emergencies. The Bureau of Consular Affairs formulates and implements policy relating to immigration and consular services and ensures responsive and efficient provision of consular services overseas.

Consular Affairs (CA) is the public face of the Department of State for millions of people around the world. CA is responsible for the welfare and protection of U.S. citizens abroad, for the issuance of passports and other documentation to citizens and nationals, and for the protection of U.S. border security and the facilitation of legitimate travel to the United States. CA also has a significant domestic presence, most notably the 29 U.S. Passport agencies and centers, 26 of which deal directly with the U.S. public. These far-reaching consular activities have broad foreign policy and domestic political implications and involve serious legal, humanitarian, and management concerns. Responsibility for these functions is vested within the Department of State in the Assistant Secretary for Consular Affairs and for their implementation abroad in consular officers assigned to embassies and consulates abroad. CA is also the Department’s largest Bureau in terms of domestic personnel and is almost entirely funded through revenue generated by consular fees. This revenue totaled $4.16 billion in 2015, making CA the equivalent of a Fortune 600 company.
        </div>
    );
};

export default About;